apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dynamic-wrapper-plugin-showcase
  title: RH1 Dynamic Frontend Wrapper Showcase
  description: |
    This is a simple showcase of dynamic frontend wrapper on RHDH.
  links:
    - title: RHDH Developer Website
      url: https://developers.redhat.com/rhdh
    - title: RHDH wrapper plugin Showcase
      url: https://showcase.janus-idp.io/
  annotations:
    argocd/app-name: 'janus-idp'
    backstage.io/kubernetes-id: 'janus-idp'
    github.com/project-slug: janus-idp/backstage-showcase
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/techdocs-ref: url:https://github.com/janus-idp/backstage-showcase
    backstage.io/kubernetes-namespace: janus-idp-prod
    sonarqube.org/project-key: janus-idp_backstage-showcase
spec:
  type: website
  system: rhdh-idp
  owner: rh1-authors
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:argocd
    - resource:obc
    - resource:keycloak
    - resource:github
